### ISSUE TITLE
How to use the test_utils.py ?

### ISSUE THREAD

**Issue by DragonLong18** [j-morano/rrwnet#1]
Dear Morano:

I am wondering how to use the test_utils.py to get the evaluation metrics. Can you give me sample code.

Thank you !

**Comment by j-morano** [comment]
Hello. The file `test_utils.py` is used by `compare_results.py`. There you can see how it works. However, if you still have questions after taking a look at this file (if you have not done so before), please feel free to contact me. Regards.

**Comment by DragonLong18** [comment]
Morano, Thank you! Best Regards!

**Comment by j-morano** [comment]
You are welcome! Happy to help. I should probably update the documentation to clarify this. Regards.

**Comment by j-morano** [comment]
Hello. Just for your information, in case you are interested. I improved the documentation and simplified the code for the evaluation. I have already committed the new version to the main branch.
